name: Build Web

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Replace environments
        run: python ./.github/workflows/replacer.py --envPath src/environments/ --apiKey ${{ secrets.apiKey }} --authDomain ${{ secrets.authDomain }} --databaseURL ${{ secrets.databaseURL }} --projectId ${{ secrets.projectId }} --storageBucket ${{ secrets.storageBucket }} --messagingSenderId ${{ secrets.messagingSenderId }} --appId ${{ secrets.appId }} --measurementId ${{ secrets.measurementId }}
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 9
      - name: Install NPM Modules
        run: |
          npm install
      - name: Build
        run: |
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI | exit 0
          ionic build --prod --verbose
